name: valorant_stats
version: 1.0.0
config-version: 2

profile: valorant_stats

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
test-paths: ["tests"]

models:
  valorant_stats:
    staging:
      +materialized: view
    marts:
      +materialized: table