-- Why: create vlr.dim_date if missing. Python ensure adds/alters columns (no DROP).
-- Grain: one calendar day. Keys support year/quarter/month/week and BETWEEN ranges.
CREATE SCHEMA IF NOT EXISTS vlr;

CREATE SEQUENCE IF NOT EXISTS vlr.seq_dim_date_row_number;

CREATE TABLE IF NOT EXISTS vlr.dim_date (
    row_number BIGINT PRIMARY KEY DEFAULT nextval('vlr.seq_dim_date_row_number'),
    date_key INTEGER NOT NULL UNIQUE,
    full_date DATE NOT NULL UNIQUE,
    project_date TEXT NOT NULL UNIQUE,
    year INTEGER NOT NULL,
    quarter INTEGER NOT NULL,
    month INTEGER NOT NULL,
    day INTEGER NOT NULL,
    day_of_year INTEGER NOT NULL,
    day_of_week INTEGER NOT NULL,
    week_of_year INTEGER NOT NULL,
    iso_year INTEGER NOT NULL,
    week_of_month INTEGER NOT NULL,
    month_name TEXT NOT NULL,
    month_short TEXT NOT NULL,
    day_name TEXT NOT NULL,
    day_short TEXT NOT NULL,
    year_month INTEGER NOT NULL,
    year_month_text TEXT NOT NULL,
    year_quarter INTEGER NOT NULL,
    year_quarter_text TEXT NOT NULL,
    year_half INTEGER NOT NULL,
    year_half_text TEXT NOT NULL,
    iso_week_num INTEGER NOT NULL,
    iso_week_key TEXT NOT NULL,
    decade INTEGER NOT NULL,
    days_in_month INTEGER NOT NULL,
    week_start DATE NOT NULL,
    week_end DATE NOT NULL,
    month_start DATE NOT NULL,
    month_end DATE NOT NULL,
    quarter_start DATE NOT NULL,
    quarter_end DATE NOT NULL,
    half_start DATE NOT NULL,
    half_end DATE NOT NULL,
    year_start DATE NOT NULL,
    year_end DATE NOT NULL,
    is_weekend BOOLEAN NOT NULL,
    is_week_start BOOLEAN NOT NULL,
    is_week_end BOOLEAN NOT NULL,
    is_month_start BOOLEAN NOT NULL,
    is_month_end BOOLEAN NOT NULL,
    is_quarter_start BOOLEAN NOT NULL,
    is_quarter_end BOOLEAN NOT NULL,
    is_half_start BOOLEAN NOT NULL,
    is_half_end BOOLEAN NOT NULL,
    is_year_start BOOLEAN NOT NULL,
    is_year_end BOOLEAN NOT NULL,
    insert_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    update_date TIMESTAMPTZ NOT NULL DEFAULT now()
);
